import { Company, User, JobOrder, Candidate, Interview, Offer } from "@/types";
import { CompanyStatus, JobOrderStatus, UserRole, CandidateStatus, InterviewStatus, InterviewLevel, OfferStatus } from "@/lib/constants/enums";

// Mock Users (with passwords for auth)
export const mockUsers: any[] = [
  {
    id: "1",
    email: "admin@ats.com",
    name: "Admin User",
    role: UserRole.ADMIN,
    password: "admin123",
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    email: "leader@ats.com",
    name: "John Leader",
    role: UserRole.LEADER,
    password: "leader123",
    createdAt: new Date("2024-01-02"),
    updatedAt: new Date("2024-01-02"),
  },
  {
    id: "3",
    email: "recruiter1@ats.com",
    name: "Sarah Recruiter",
    role: UserRole.RECRUITER,
    password: "recruiter123",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
  {
    id: "4",
    email: "recruiter2@ats.com",
    name: "Mike Recruiter",
    role: UserRole.RECRUITER,
    password: "recruiter123",
    createdAt: new Date("2024-01-03"),
    updatedAt: new Date("2024-01-03"),
  },
];

// Initialize localStorage with mock users if not exists
if (typeof window !== "undefined") {
  const existingUsers = localStorage.getItem("ats_users");
  if (!existingUsers) {
    localStorage.setItem("ats_users", JSON.stringify(mockUsers));
  }
}

// Mock Companies
export const mockCompanies: Company[] = [
  {
    id: "c1",
    name: "Tech Corp",
    industry: "Technology",
    location: "San Francisco, CA",
    contactEmail: "hr@techcorp.com",
    contactPhone: "+1-555-0101",
    status: CompanyStatus.ACTIVE,
    createdBy: "2",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
  },
  {
    id: "c2",
    name: "Finance Solutions",
    industry: "Finance",
    location: "New York, NY",
    contactEmail: "contact@financesol.com",
    contactPhone: "+1-555-0102",
    status: CompanyStatus.ACTIVE,
    createdBy: "2",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
  },
  {
    id: "c3",
    name: "Healthcare Plus",
    industry: "Healthcare",
    location: "Boston, MA",
    contactEmail: "jobs@healthplus.com",
    status: CompanyStatus.ACTIVE,
    createdBy: "2",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
];

// Mock Job Orders
export const mockJobOrders: JobOrder[] = [
  {
    id: "j1",
    companyId: "c1",
    title: "Senior Full Stack Developer",
    description: "Looking for an experienced full stack developer with React and Node.js expertise.",
    requirements: "5+ years experience, React, Node.js, TypeScript, AWS",
    location: "San Francisco, CA (Hybrid)",
    salaryRange: "$140k - $180k",
    positions: 2,
    status: JobOrderStatus.OPEN,
    createdBy: "2",
    assignedRecruiters: ["3", "4"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-01-20"),
  },
  {
    id: "j2",
    companyId: "c1",
    title: "DevOps Engineer",
    description: "Seeking DevOps engineer to manage cloud infrastructure.",
    requirements: "3+ years DevOps, Kubernetes, Docker, CI/CD",
    location: "San Francisco, CA (Remote)",
    salaryRange: "$120k - $160k",
    positions: 1,
    status: JobOrderStatus.OPEN,
    createdBy: "2",
    assignedRecruiters: ["3"],
    createdAt: new Date("2024-01-21"),
    updatedAt: new Date("2024-01-21"),
  },
  {
    id: "j3",
    companyId: "c2",
    title: "Financial Analyst",
    description: "Financial analyst for investment banking division.",
    requirements: "MBA, 3+ years finance, Excel, SQL",
    location: "New York, NY (On-site)",
    salaryRange: "$100k - $130k",
    positions: 1,
    status: JobOrderStatus.OPEN,
    createdBy: "2",
    assignedRecruiters: ["4"],
    createdAt: new Date("2024-01-22"),
    updatedAt: new Date("2024-01-22"),
  },
  {
    id: "j4",
    companyId: "c3",
    title: "Registered Nurse",
    description: "RN for ICU department.",
    requirements: "RN license, 2+ years ICU experience",
    location: "Boston, MA (On-site)",
    salaryRange: "$75k - $95k",
    positions: 3,
    status: JobOrderStatus.OPEN,
    createdBy: "2",
    assignedRecruiters: [],
    createdAt: new Date("2024-01-23"),
    updatedAt: new Date("2024-01-23"),
  },
];

// Mock Candidates
export const mockCandidates: Candidate[] = [
  {
    id: "cand1",
    jobOrderId: "j1",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@email.com",
    phone: "+1-555-1001",
    resumeUrl: "https://example.com/resume1.pdf",
    linkedinUrl: "https://linkedin.com/in/alicejohnson",
    status: CandidateStatus.CONTACTED,
    addedBy: "3",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-26"),
  },
  {
    id: "cand2",
    jobOrderId: "j1",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@email.com",
    phone: "+1-555-1002",
    status: CandidateStatus.NO_CONTACT,
    addedBy: "3",
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-01-25"),
  },
  {
    id: "cand3",
    jobOrderId: "j2",
    firstName: "Carol",
    lastName: "Davis",
    email: "carol.davis@email.com",
    phone: "+1-555-1003",
    linkedinUrl: "https://linkedin.com/in/caroldavis",
    status: CandidateStatus.NEXT_INTERVIEW,
    addedBy: "3",
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-27"),
  },
  {
    id: "cand4",
    jobOrderId: "j3",
    firstName: "David",
    lastName: "Wilson",
    email: "david.wilson@email.com",
    status: CandidateStatus.REJECTED,
    addedBy: "4",
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-27"),
  },
];

// Mock Interviews
export const mockInterviews: Interview[] = [
  {
    id: "iv1",
    candidateId: "cand1",
    jobOrderId: "j1",
    level: InterviewLevel.L1,
    scheduledAt: new Date("2024-01-28T10:00:00"),
    status: InterviewStatus.COMPLETED,
    feedback: "Strong technical skills, good communication. Recommended for L2.",
    interviewerName: "John Tech Lead",
    createdBy: "3",
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-28"),
  },
  {
    id: "iv2",
    candidateId: "cand1",
    jobOrderId: "j1",
    level: InterviewLevel.L2,
    scheduledAt: new Date("2024-02-02T14:00:00"),
    status: InterviewStatus.SCHEDULED,
    interviewerName: "Sarah Manager",
    createdBy: "3",
    createdAt: new Date("2024-01-29"),
    updatedAt: new Date("2024-01-29"),
  },
  {
    id: "iv3",
    candidateId: "cand3",
    jobOrderId: "j2",
    level: InterviewLevel.L1,
    scheduledAt: new Date("2024-01-27T11:00:00"),
    status: InterviewStatus.COMPLETED,
    feedback: "Excellent DevOps knowledge. Ready for next round.",
    interviewerName: "Mike DevOps",
    createdBy: "3",
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-27"),
  },
  {
    id: "iv4",
    candidateId: "cand4",
    jobOrderId: "j3",
    level: InterviewLevel.L1,
    scheduledAt: new Date("2024-01-27T15:00:00"),
    status: InterviewStatus.COMPLETED,
    feedback: "Not a good fit for the role. Lacks required finance experience.",
    interviewerName: "Lisa Finance Head",
    createdBy: "4",
    createdAt: new Date("2024-01-26"),
    updatedAt: new Date("2024-01-27"),
  },
];

// Mock Offers
export const mockOffers: Offer[] = [
  {
    id: "offer1",
    candidateId: "cand1",
    jobOrderId: "j1",
    offeredRole: "Senior Full Stack Developer",
    offeredSalary: "$160,000",
    expectedJoiningDate: new Date("2024-02-15"),
    offerNotes: "Competitive package with benefits and sign-on bonus.",
    status: OfferStatus.OFFERED,
    createdBy: "3",
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-01"),
  },
];
